# Project Name
TARGET = MonoSeed09

# Sources
CPP_SOURCES = \
	MonoSeed09.cpp \
	../../Hardware/PotentiometerArray/PotentiometerArray.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
