# Project Name
TARGET = StandaloneTest

# Sources
CPP_SOURCES = \
	StandaloneTest.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
