# Project Name
TARGET = BassSeed303

# Sources
CPP_SOURCES = \
	BassSeed303.cpp \
	SynthEngine.cpp \
	../../Hardware/StepSequencer/Drivers/Keys.cpp \
	../../Hardware/StepSequencer/Drivers/Leds.cpp \
	../../Hardware/StepSequencer/Drivers/SequencerBrain.cpp \
	../../Hardware/StepSequencer/Drivers/StepSequencer.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
