# Project Name
TARGET = BassSeed303

# Sources
CPP_SOURCES = \
	BassSeed303.cpp \
	SynthEngine.cpp \
	../../Hardware/StepSequencerInterface/Drivers/Keys.cpp \
	../../Hardware/StepSequencerInterface/Drivers/Leds.cpp \
	../../Hardware/StepSequencerInterface/Drivers/StepSequencerInterface.cpp \
	../../Hardware/StepSequencerInterface/Drivers/Controller.cpp \
	../../Hardware/StepSequencerInterface/Drivers/StepSequencer.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
