# Project Name
TARGET = BassSeed303

# Sources
CPP_SOURCES = \
	BassSeed303.cpp \
	SynthEngine.cpp \
	../../Hardware/StepSequencer/Drivers/Keys.cpp \
	../../Hardware/StepSequencer/Drivers/Leds.cpp \
	../../Hardware/StepSequencer/Drivers/Interface.cpp \
	../../Hardware/StepSequencer/Drivers/Controller.cpp \
	../../Hardware/StepSequencer/Drivers/StepSequencer.cpp \
	../../Hardware/StepSequencer/Drivers/StepIndicator.cpp \
	../../Hardware/StepSequencer/Drivers/PlayState.cpp \
	../../Hardware/StepSequencer/Drivers/SetSeqSyncState.cpp \
	../../Hardware/StepSequencer/Drivers/StepRecState.cpp \
	../../Hardware/StepSequencer/Drivers/StopState.cpp \
	../../Hardware/PotentiometerArray/Drivers/PotentiometerArray.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
