# Project Name
TARGET = DriverTest

# Sources
CPP_SOURCES = \
	DriverTest.cpp \
	../../Drivers/ExternalCodec.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
