# Project Name
TARGET = Interface.test

# Sources
CPP_SOURCES = \
	Interface.test.cpp \
	../../Drivers/Keys.cpp \
	../../Drivers/Leds.cpp \
	../../Interface.cpp \
	../../Drivers/Controller.cpp \
	../../Drivers/StepSequencer.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
