# Project Name
TARGET = StandaloneTest

# Sources
CPP_SOURCES = \
	StandaloneTest.cpp \
	../../Drivers/Keys.cpp \
	../../Drivers/Leds.cpp \
	../../SequencerBrain.cpp \
	../../StepSequencer.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
