# Project Name
TARGET = NavigationKeyboard.test

# Sources
CPP_SOURCES = \
	NavigationKeypad.test.cpp \
	../../Drivers/NavigationKeypad.cpp 

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile