test:
	g++ -lstdc++ -o Controller.test.exe -DTESTING \
		Controller.test.cpp \
		../../Drivers/Controller.cpp \
		../../Drivers/StepIndicator.cpp \
		../../Drivers/BlinkState.cpp \
		../../Drivers/PlayState.cpp \
		../../Drivers/SaveState.cpp \
		../../Drivers/SetSeqSyncState.cpp \
		../../Drivers/StepRecState.cpp \
		../../Drivers/StopState.cpp 

clean:
	rm -f rm -fR build
