test:
	g++ -lstdc++ -o Controller.test.exe -DTESTING \
		Controller.test.cpp \
		../../Drivers/Controller.cpp \
		../../Drivers/StepIndicator.cpp \
		../../Drivers/StopState.cpp 

clean:
	rm -f rm -fR build
