# Project Name
TARGET = main.cpp

# Sources
CPP_SOURCES = \
	main.cpp \
	../../Hardware/PotentiometerArray/Drivers/PotentiometerArray.cpp 

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
