# Project Name
TARGET = MultipleValueTest

# Sources
CPP_SOURCES = \
	MultipleValueTest.cpp \
	../../Drivers/PotentiometerArray.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

LDFLAGS += -u _printf_float
