# Project Name
#TARGET = Test

# Sources
#CPP_SOURCES = \
#	Test.cpp 

# Core location, and generic Makefile.
# SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
# include $(SYSTEM_FILES_DIR)/Makefile

test:
	g++ Test.cpp -lstdc++ -o my_output

clean:
	rm -f rm -fR build
