# Project Name
TARGET = SingleValueTest

# Sources
CPP_SOURCES = \
	SingleValueTest.cpp 

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
