# Project Name
TARGET = SimpleOsc

# Sources
CPP_SOURCES = \
	SimpleOsc.cpp \
	../../Hardware/PotentiometerArray/PotentiometerArray.cpp

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
